services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
      - ./secuencia.json:/app/secuencia.json
      - ./actas:/app/actas
      - ./error.txt:/app/error.txt
      - ./secuencia.json:/app/secuencia.json